{
    'name': 'Zen Theme',
    'description': 'Zen Theme',
    'category': 'Website',
    'version': '1.0',
    'author': 'OpenERP SA',
    'depends': ['website', 
                'account',
                'account_followup',
                'boss_default_report',
    ],
    'data': [
        'views/layout.xml',
        'views/pages.xml',
        'views/snippets.xml',
        'views/images.xml',
        'views/options.xml',
        'report/boss_header_G002.xml',
        'report/boss_invoice_orange.xml',
        'report/boss_invoice_O002.xml',
        'report/boss_invoice_G001.xml',
        'report/boss_invoice_G002.xml',
        'report/boss_invoice_B001.xml',
        'report/boss_invoice_B002.xml',
        'report/boss_invoice_I001.xml',
        'report/boss_overdue_B001.xml',
        'report/boss_overdue_B002.xml',
        'report/boss_followup_B001.xml',
        'report/boss_followup_O001.xml',
        'data/boss_followup_reports.xml',
        'data/boss_followup_reports_O001.xml',
        'data/boss_partner_reports.xml',
    ],
    'application': True,
}
